export const filterData = [{name:"Fast",id:"0"},
                    {name:"Fish",id:"1"},
                    {name:"Salads",id:"2"},
                    {name:"Chicken",id:"3"},
                    {name:"Beef",id:"4"},
                    {name:"Chicken soup",id:"5"},
                    {name:"Quick and Easy",id:"6"},
                    {name:"Vegan",id:"7"},
                    {name:"Spaghetti",id:"8"},
                    {name:"Italian",id:"9"},
                    {name:"Korean",id:"10"},
                    {name:"Healthy",id:"11"},
                    {name:"Indian",id:"12"},
                    {name:"Tofu",id:"13"}
                ];
